version: 2
jobs:
  one:
    build:
      docker:
        - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - run: echo "A first hello"
  two:
    build:
      docker:
        - image: circleci/ruby:2.4.1
      steps:
        - checkout
        - image: echo "Justin hello"
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
